### ISSUE TITLE
Two handed tracking fix 

### ISSUE THREAD

**Issue by sidequestlegend** [postbeta/Discontinue#2]
Hi there, I noticed that only one hand seems to exist at any time. I havent looked at the apk but im wondering if you have this line in the manifest which quest requires to fix hand tracking issues. 

```
<uses-feature android:name="android.hardware.vr.headtracking" android:required="true" android:version="1"/>
```

[More Info](https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/?utm_medium=android_app&utm_source=share)

Im shane BTW, i run SideQuest. Feel free to coordinate with me on this release. Easiest place to get me is [discord](https://discord.gg/2bkwecn). Thanks for an awesome app!

**Comment by shaneharris** [comment]
fixed in https://github.com/postbeta/Discontinue/blob/master/Quest/DiscontinueQuestV004.apk
